apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-admin-binding
subjects:
  - kind: User
    name: gils339  # Kubernetes user from aws-auth ConfigMap
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin  # Full admin access
  apiGroup: rbac.authorization.k8s.io

