apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
     containers:
     - name: my-app-container
       image: 114885604022.dkr.ecr.eu-central-1.amazonaws.com/2bcloud-repo-dev
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
spec:                                                                                                                type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: my-application
